/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package factory;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Factory classUnderTest = new Factory();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
